name: SonarQube
on:
  push:
    branches:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install SFDX
        run: |
          node --version
          npm install -g sfdx-cli
          export SFDX_DISABLE_DNS_CHECK=true
          echo "Version of SFDX CLI is: $(sfdx --version)"
      
      - name: Run Apex Tests
        run: |
          cd src
          sfdx apex run test -l RunLocalTests --loglevel=trace -y -c -r json -d ./tests/apex -w 999999

      - name: "Run LWC Jest tests"
        run: |
          cd src
          echo "Installing npm by command 'npm install'"
          npm install
          echo "Installing jest by command 'npm install @salesforce/sfdx-lwc-jest --save-dev'"
          npm install @salesforce/sfdx-lwc-jest --save-dev
          echo "Running Jest unit tests"
          npm run test:unit

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}